name: Transforming with pandoc

on: [push]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create output HTML directory
      id: output_HTML_directory
      run: |
        mkdir OUTPUT_HTML_DIR # create output dir
        # this will also include README.md
        echo "::set-output name=files::$(printf '"%s" ' *.md)"
    - uses: docker://pandoc/latex:3.0
      with:
        args: >- # allows you to break string into multiple lines
           --toc  
           -f latex 
           -s --csl apalike.csl 
           --bibliography=BIBLIOGRAPHY/biblio.bib
           --output=OUTPUT_HTML_DIR ${{ steps.files_list.outputs.files }}
    - uses: actions/upload-artifact@master
      with:
        name: OUTPUT_HTML_DIR
        path: OUTPUT_HTML_DIR
