name: Transforming with pandoc

on: [push]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create output HTML directory
      id: output_HTML_directory
      run: |
        mkdir output_HTML_directory # create output dir
        # this will also include README.md
        echo "::set-output name=files::$(printf '"%s" ' *.md)"
    - uses: docker://pandoc/latex:3.0
      with:
        args: >- # allows to break string into multiple lines
           --toc  
           -f latex 
           -s --csl 
           --bibliography=BIBLIOGRAPHY/biblio.bib
           -t chunkedhtml ${{ steps.output_HTML_directory.outputs.files }}
    - uses: actions/upload-artifact@master
      with:
        name: output
        path: output
