name: Transforming with pandoc

on: [push]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
    - uses: docker://pandoc/core:3.0
      with:
        args: >- # allows you to break string into multiple lines
           --toc  
           -f latex 
           #-t chunkedhtml  
           -s --csl apalike.csl 
           --bibliography=BIBLIOGRAPHY/biblio.bib 
    - name: Publish the web pages
      uses:  peaceiris/actions-gh-pages@v3
      with:
        # ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # PUBLISH_BRANCH: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
