name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create output HTML directory
        id: files_list
        run: |
          mkdir output  # create output dir
          # this will also include README.md
          echo "::set-output name=files::$(printf '"%s" ' *.md)"

      - uses: docker://pandoc/latex:3.0
        with:
          args: --toc -s -csl -t latex main.tex --bibliography=BIBLIOGRAPHY/biblio.bib --metadata title="HTML_dir" -t chunkedhtml --output=output/result.zip ${{ steps.files_list.outputs.files }}
          
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
       
