name: Transforming with pandoc
on: [push]
jobs:
    job1:
		convert_via_pandoc:
		runs-on: ubuntu-latest
	      steps:
	      - uses: actions/checkout@v2
	      - name: create output zipped HTML directory
	        id: output_HTML_directory.zip
	        run: |
	          mkdir output_HTML_directory  # create final output dir
	          echo "::set-output name=files::$(printf '"%s" ' *.md)"
	      - uses: docker://pandoc/latex:3.0
	        with:
	          args: >- # allows to break string into multiple lines
	            --toc  
	            -f latex 
	            -s --csl 
	            --bibliography=BIBLIOGRAPHY/biblio.bib
	            --metadata title="OUTPUT_HTML_directory"
	            -t chunkedhtml output.zip 
    job2:
      if: ${{ always() }}
      needs: job1 
        transfer_pandoc:
	        runs-on: ubuntu-latest
          steps:
            - uses: docker://pandoc/latex:3.0
              with:
                args: --output=output/result.zip ${{ steps.files_list.outputs.files }}
	          - uses: actions/upload-artifact@master
	            with:
	              name: output_HTML_directory
	              path: output_HTML_directory

